name: AWS workflow

on:
  push

env:
  BUCKET_NAME:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps: 
      - name: